spring.datasource.url=jdbc:h2:mem:survey_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# JWT Secret (at least 256 bits for HS256)
app.jwt.secret=9a4f4e3545674c91a7c7395a666114eb25bc9202167d64372912443652a926a5
app.jwt.expiration-ms=86400000
spring.jpa.defer-datasource-initialization=true
